### ISSUE TITLE
Add a border

### ISSUE THREAD

**Issue by OeildeLynx31** [ScratchTutorials/ScratchTutorials#19]
Can anyone add a grey border in the tables, please ? I can't do it, and and if not, they are very unreadable.
Example:
[Before](https://oeildelynx.top7box.com/wordpress/wp-content/uploads/2022/05/before.png) | [after](https://oeildelynx.top7box.com/wordpress/wp-content/uploads/2022/05/before.png)
Thank you !

PS: Can you check this checkbox when it's finish ?
- [ ] It is finish

**Comment by Lockstart** [comment]
Sorry, but the design is made like that.

**Comment by OeildeLynx31** [comment]
Yes, but if the design is unreadable, people don't want go here !

**Comment by Lockstart** [comment]
It isn't unreadable...
And I prefer to avoid changing the design.
