### ISSUE TITLE
Can we translate the tutorials into other languages ?

### ISSUE THREAD

**Issue by OeildeLynx31** [ScratchTutorials/ScratchTutorials#22]
Can we translate the tutorials into other languages ?
It would be good. And then I already have an example of what we could do:
[Here](https://tuto-scratch.pages.dev/tutorials/Scratch%20Emojis/index-test)
I think it is a good idea, but I am waiting for your answer. 
Thank you !

**Comment by OeildeLynx31** [comment]
As I don't have an answer, I put the language option for this tutorial, if someone does not agree, I will delete it.

**Comment by 4ntidot** [comment]
#26
